---
- hosts: test1 # group of hosts
  gather_facts: yes # we need to gather facts
  become: true
  roles:
   - users
   - http

- hosts: test2 # group of hosts
  gather_facts: yes # we need to gather facts
  become: true
  roles:
   - users
   - php

